server {
    listen 80;
    server_name slls.asia www.slls.asia;

    location /.well-known/acme-challenge/ {
        root /usr/share/nginx/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name slls.asia www.slls.asia;

    ssl_certificate /etc/nginx/ssl/live/slls.asia/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/live/slls.asia/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    location = /admin {
        return 301 /admin/;
    }

    location /admin/ {
        proxy_pass http://study-plan-admin:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://study-plan-frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
