<template>
  <view class="page" v-if="plan">
    <view class="hero"><view class="hero-top"><view><view class="kicker">计划详情</view><view class="title">{{ plan.title }}</view></view><view class="pill">{{ statusText(plan.status) }}</view></view><view class="description">{{ plan.description || '暂无计划说明' }}</view><view class="range">{{ plan.start_date }} 至 {{ plan.end_date }} · 每周 {{ plan.weekly_target_hours }} 小时</view><view class="progress-copy"><text>完成 {{ completed }}/{{ tasks.length }}</text><text>{{ progress }}%</text></view><view class="track"><view class="fill" :style="{width:`${progress}%`} " /></view></view>
    <view class="actions"><button @click="openPlanEdit">编辑计划</button><button @click="openInvite">邀请伙伴</button><button @click="toggleStatus">{{ plan.status==='paused'?'恢复计划':'暂停计划' }}</button><button @click="delay">延期</button><button class="danger" @click="removePlan">删除</button></view>
    <view class="properties"><view><text>学习日</text><view class="property-value">{{ weekdaySummary(plan.study_weekdays) }}</view></view><view><text>默认时段</text><view class="property-value">{{ plan.default_planned_start }}-{{ plan.default_planned_end }}</view></view><view><text>小组可见</text><view class="property-value">{{ plan.public_to_group?'是':'否' }}</view></view><view><text>来源</text><view class="property-value">{{ plan.ai_generated?'AI 生成':'手动创建' }}</view></view></view>
    <view class="section-head"><view>任务安排</view><button @click="openTaskEdit()">＋ 新建任务</button></view>
    <view class="empty" v-if="!tasks.length">这个计划还没有任务</view>
    <view class="task" v-for="task in tasks" :key="task.id" @click="openTask(task)"><view class="task-date">{{ task.date }} · {{ task.planned_start }}-{{ task.planned_end }}</view><view class="task-head"><view class="task-title">{{ task.title }}</view><view class="task-status">{{ taskStatus(task.status) }}</view></view><view class="objective">{{ task.objective }}</view><view class="task-actions" @click.stop><button @click="openTaskEdit(task)">编辑</button><button class="danger" v-if="task.status!=='in_progress'" @click="removeTask(task)">删除</button></view></view>

    <view class="sheet" v-if="planEditing" @click.self="planEditing=false"><view class="sheet-body"><view class="sheet-title">编辑计划</view><view class="field"><text>名称</text><input v-model="planForm.title" /></view><view class="field"><text>说明</text><textarea v-model="planForm.description" /></view><view class="field"><text>每周目标小时</text><input type="number" v-model.number="planForm.weekly_target_hours" /></view><view class="sheet-actions"><button class="secondary" @click="planEditing=false">取消</button><button class="primary" @click="savePlan">保存</button></view></view></view>
    <view class="sheet" v-if="taskEditing" @click.self="taskEditing=false"><view class="sheet-body"><view class="sheet-title">{{ taskForm.id?'编辑任务':'新建任务' }}</view><view class="field"><text>日期</text><picker mode="date" :value="taskForm.date" @change="taskForm.date=$event.detail.value"><view class="picker">{{ taskForm.date }}</view></picker></view><view class="field"><text>标题</text><input v-model="taskForm.title" /></view><view class="field"><text>目标</text><textarea v-model="taskForm.objective" /></view><view class="field"><text>说明</text><textarea v-model="taskForm.description" /></view><view class="grid"><picker mode="time" :value="taskForm.planned_start" @change="taskForm.planned_start=$event.detail.value"><view class="picker">{{ taskForm.planned_start }}</view></picker><picker mode="time" :value="taskForm.planned_end" @change="taskForm.planned_end=$event.detail.value"><view class="picker">{{ taskForm.planned_end }}</view></picker></view><view class="sheet-actions"><button class="secondary" @click="taskEditing=false">取消</button><button class="primary" @click="saveTask">保存</button></view></view></view>
    <view class="sheet" v-if="inviting" @click.self="inviting=false"><view class="sheet-body"><view class="sheet-title">按昵称邀请</view><input v-model="query" placeholder="至少输入 2 个字符" @input="search" /><view class="candidate" v-for="user in results" :key="user.invite_target_id" @click="sendInvite(user)">{{ user.nickname }}<text>邀请</text></view><view class="empty" v-if="query.length>=2&&!searching&&!results.length">没有找到匹配用户</view></view></view>
  </view>
</template>

<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { onLoad, onShow } from '@dcloudio/uni-app'
import { PlanApi, StudyTaskApi, UserApi, type Plan, type TimerTask, type UserSearchResult } from '@/api'
import { localDateKey } from '@/utils/date'

const planId=ref(0),plan=ref<Plan|null>(null),tasks=ref<TimerTask[]>([]),planEditing=ref(false),taskEditing=ref(false),inviting=ref(false),query=ref(''),results=ref<UserSearchResult[]>([]),searching=ref(false)
const planForm=reactive({title:'',description:'',weekly_target_hours:0}),taskForm=reactive({id:0,date:'',title:'',objective:'',description:'',planned_start:'20:00',planned_end:'21:00'})
const completed=computed(()=>tasks.value.filter(task=>task.status==='completed').length),progress=computed(()=>tasks.value.length?Math.round(completed.value/tasks.value.length*100):0)
let searchTimer:ReturnType<typeof setTimeout>|null=null
onLoad((options:any)=>{planId.value=Number(options?.id||0);if(options?.invite==='1')inviting.value=true});onShow(load)
async function load(){if(!planId.value)return;try{const [detail,rows]=await Promise.all([PlanApi.get(planId.value),PlanApi.tasks(planId.value)]);plan.value=detail;tasks.value=rows||[]}catch(error:any){uni.showToast({title:error?.message||'加载失败',icon:'none'})}}
function openPlanEdit(){if(!plan.value)return;Object.assign(planForm,{title:plan.value.title,description:plan.value.description||'',weekly_target_hours:plan.value.weekly_target_hours});planEditing.value=true}
async function savePlan(){if(!planForm.title.trim())return void uni.showToast({title:'请填写计划名称',icon:'none'});try{plan.value=await PlanApi.update(planId.value,{...planForm});planEditing.value=false;await load()}catch(error:any){uni.showToast({title:error?.message||'保存失败',icon:'none'})}}
function openTaskEdit(task?:TimerTask){Object.assign(taskForm,task?{id:task.id,date:task.date,title:task.title,objective:task.objective,description:task.description||'',planned_start:task.planned_start||'20:00',planned_end:task.planned_end||'21:00'}:{id:0,date:plan.value?.start_date||localDateKey(),title:'',objective:'',description:'',planned_start:plan.value?.default_planned_start||'20:00',planned_end:plan.value?.default_planned_end||'21:00'});taskEditing.value=true}
async function saveTask(){if(!taskForm.title.trim()||!taskForm.objective.trim()||taskForm.planned_start>=taskForm.planned_end)return void uni.showToast({title:'请完整填写有效任务信息',icon:'none'});const data={date:taskForm.date,title:taskForm.title,objective:taskForm.objective,description:taskForm.description,planned_start:taskForm.planned_start,planned_end:taskForm.planned_end};try{taskForm.id?await StudyTaskApi.update(taskForm.id,data):await PlanApi.createTask(planId.value,data);taskEditing.value=false;await load()}catch(error:any){uni.showToast({title:error?.message||'保存失败',icon:'none'})}}
async function toggleStatus(){if(!plan.value)return;try{plan.value=plan.value.status==='paused'?await PlanApi.resume(planId.value):await PlanApi.pause(planId.value)}catch(error:any){uni.showToast({title:error?.message||'操作失败',icon:'none'})}}
async function delay(){const result=await new Promise<any>(resolve=>uni.showActionSheet({itemList:['延期 1 天','延期 3 天','延期 7 天'],success:resolve,fail:()=>resolve(null)}));if(!result)return;try{await PlanApi.delay(planId.value,[1,3,7][result.tapIndex]);await load()}catch(error:any){uni.showToast({title:error?.message||'延期失败',icon:'none'})}}
async function removePlan(){if(!plan.value)return;const confirmed=await confirm('删除计划',`将删除「${plan.value.title}」及其任务和打卡历史。`);if(!confirmed)return;try{await PlanApi.remove(planId.value);uni.navigateBack()}catch(error:any){uni.showToast({title:error?.message||'删除失败',icon:'none'})}}
async function removeTask(task:TimerTask){if(!await confirm('删除任务',`确认删除「${task.title}」？`))return;try{await StudyTaskApi.remove(task.id);await load()}catch(error:any){uni.showToast({title:error?.message||'删除失败',icon:'none'})}}
function confirm(title:string,content:string){return new Promise<boolean>(resolve=>uni.showModal({title,content,confirmColor:'#c95668',success:result=>resolve(result.confirm)}))}
function openInvite(){query.value='';results.value=[];inviting.value=true}function search(){if(searchTimer)clearTimeout(searchTimer);results.value=[];if(query.value.trim().length<2)return;searchTimer=setTimeout(async()=>{searching.value=true;try{results.value=await UserApi.search(query.value.trim())}finally{searching.value=false}},300)}
async function sendInvite(user:UserSearchResult){try{await PlanApi.invite(planId.value,user.invite_target_id);inviting.value=false;uni.showToast({title:'邀请已发送',icon:'success'})}catch(error:any){uni.showToast({title:error?.message||'邀请失败',icon:'none'})}}
function openTask(task:TimerTask){uni.navigateTo({url:`/pages/task/task?id=${task.id}`})}function statusText(status:string){return status==='paused'?'已暂停':status==='archived'?'已归档':'进行中'}function taskStatus(status:string){return status==='completed'?'已完成':status==='in_progress'?'学习中':'待执行'}
function weekdaySummary(selected:number[]=[]){const labels=['一','二','三','四','五','六','日'];return selected.length===7?'每天':selected.length?`周${selected.map(value=>labels[value-1]).join('、')}`:'按指定日期'}
</script>

<style lang="scss">
.page{min-height:100vh;box-sizing:border-box;padding:28rpx 28rpx 70rpx;background:linear-gradient(180deg,#fff0f7,#fffaf0 44%,#f7fbff);color:#4b2b3f}.hero{padding:34rpx;border-radius:34rpx;background:linear-gradient(135deg,#ff8fab,#ffc36a);color:#fff}.hero-top,.progress-copy,.task-head,.section-head{display:flex;align-items:center;justify-content:space-between;gap:16rpx}.kicker{font-size:22rpx}.title{margin-top:8rpx;font-size:40rpx;font-weight:900}.pill{padding:9rpx 16rpx;border-radius:99rpx;background:#ffffff35}.description,.range{margin-top:16rpx;font-size:24rpx;line-height:1.5}.progress-copy{margin-top:24rpx}.track{height:14rpx;margin-top:10rpx;border-radius:99rpx;background:#ffffff45;overflow:hidden}.fill{height:100%;background:#fff}.actions{display:grid;grid-template-columns:repeat(3,1fr);gap:10rpx;margin-top:18rpx}.actions button,.task-actions button{margin:0;padding:0 8rpx;background:#fff;color:#d85e82;font-size:22rpx}.danger{color:#bd5361!important}.properties{display:grid;grid-template-columns:1fr 1fr;gap:12rpx;margin-top:18rpx}.properties>view{padding:22rpx;border-radius:20rpx;background:#fff}.properties text{display:block;color:#8a92a6;font-size:21rpx}.property-value{margin-top:7rpx;font-size:24rpx;font-weight:700}.section-head{margin:32rpx 4rpx 16rpx;font-size:31rpx;font-weight:900}.section-head button{margin:0;background:#fff0f6;color:#ff6f91;font-size:22rpx}.task{margin-bottom:16rpx;padding:26rpx;border-radius:26rpx;background:#fff;border:1rpx solid #ffe0ea}.task-date{color:#9a6176;font-size:22rpx}.task-head{margin-top:10rpx}.task-title{font-size:29rpx;font-weight:900}.task-status{color:#ff6f91;font-size:21rpx}.objective{margin-top:10rpx;color:#606a80;font-size:24rpx;line-height:1.5}.task-actions{display:flex;justify-content:flex-end;gap:10rpx;margin-top:16rpx}.task-actions button{height:54rpx;line-height:54rpx}.empty{padding:30rpx;color:#8a92a6;text-align:center}.sheet{position:fixed;inset:0;z-index:99;display:flex;align-items:flex-end;background:#30222b75}.sheet-body{width:100%;max-height:88vh;box-sizing:border-box;padding:34rpx 30rpx 44rpx;border-radius:30rpx 30rpx 0 0;background:#fff;overflow-y:auto}.sheet-title{margin-bottom:24rpx;font-size:34rpx;font-weight:900}.field{margin-bottom:18rpx}.field text{display:block;margin-bottom:8rpx;color:#606a80}input,textarea,.picker{box-sizing:border-box;width:100%;padding:0 20rpx;border:1rpx solid #dfe4ed;border-radius:14rpx;background:#f9fbff;font-size:25rpx}input,.picker{height:76rpx;line-height:76rpx}textarea{height:120rpx;padding-top:16rpx}.grid,.sheet-actions{display:grid;grid-template-columns:1fr 1fr;gap:14rpx}.sheet-actions{margin-top:24rpx}.primary{background:linear-gradient(135deg,#ff7aa2,#ffb45c);color:#fff}.secondary{background:#f3f6fb;color:#606a80}.candidate{display:flex;justify-content:space-between;margin-top:12rpx;padding:22rpx;border-radius:16rpx;background:#f8faff}.candidate text{color:#ff6f91}
</style>
